# Generated by Django 3.2.8 on 2021-10-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='checker',
            field=models.TextField(default='blank', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='url_path',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='url_path',
            field=models.CharField(default='blank', max_length=100),
            preserve_default=False,
        ),
    ]
