# Generated by Django 3.2.8 on 2022-02-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_labs', '0002_auto_20211019_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='question',
            field=models.TextField(),
        ),
    ]
