# Generated by Django 3.2.8 on 2022-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_labs', '0003_alter_lesson_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='checker',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
