# Generated by Django 3.2.8 on 2022-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_labs', '0004_alter_lesson_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hints',
            field=models.TextField(blank=True),
        ),
    ]
