# Generated by Django 3.2.8 on 2022-02-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_labs', '0005_lesson_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assertions',
            field=models.TextField(blank=True),
        ),
    ]
