# Generated by Django 3.2.8 on 2022-03-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_labs', '0008_auto_20220226_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_lesson',
            name='date_completed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
